apiVersion: apps/v1
kind: Deployment  
metadata:
  name: student-app
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  strategy: 
    type: RollingUpdate 
  template: 
    metadata: 
      labels:
        app: student-app
    spec:
      containers:
      - name: student-app
        image: darsh8699/studentapp:studentapp1
        ports:
        - name: tomcat
          containerPort: 8080
          protocol: TCP 
