apiVersion: apps/v1
kind: Deployment  
metadata:
  name: studentdb
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: studentdb
  strategy: 
    type: RollingUpdate 
  template: 
    metadata: 
      labels:
        app: studentdb
    spec:
      containers:
      - name: studentdb 
        image: darsh8699/studentapp:database1
        ports:
        - name: java
          containerPort: 8080
          protocol: TCP 
