apiVersion: apps/v1
kind: Deployment  
metadata:
  name: studentdb
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: studentdb
  strategy: 
    type: RollingUpdate 
  template: 
    metadata: 
      labels:
        app: studentdb
    spec:
      containers:
      - name: studentdb 
        image: darsh8699/studentapp:database1   # replace it with your docker image repo and tag 
        ports:
        - name: java
          containerPort: 3306   # make sure same port is exposed in Dockerfile (if doesn't exposed any port so you can use any available port)
          protocol: TCP 
