apiVersion: apps/v1
kind: Deployment  
metadata:
  name: proxy-forward-studentapp
  labels:
    app: proxy-forward-studentapp
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: proxy-forward-studentapp
  strategy: 
    type: RollingUpdate 
  template: 
    metadata: 
      labels:
        app: proxy-forward-studentapp
    spec:
      containers:
      - name: proxy-forward-studentapp-container 
        image: aakashshinde09/demo:pro
        ports:
        - name: proxy
          containerPort: 80
          protocol: TCP 
